version: '3.8'

services:
  menu-management-service:
    image: fquea/menu-management-service:1.0
    ports:
      - "4000:4000"
    environment:
      PORT_MENU_MANAGEMENT_SERVICE: 4000
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
    networks:
      - red
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.nodo == worker-1

networks:
  red:
    external: true
