version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: qjcoder
      MONGO_INITDB_ROOT_PASSWORD: qjcoder
    networks:
      - red

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      PORT_GATEWAY: 3000
      TEST_SERVICE_URL: "http://test-service:3100"
    networks:
      - red
    depends_on:
      - mongodb
    #volumes:
    #- ./backend/shared-models:/app/src/models

  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    environment:
      PORT_USERS_SERVICE: 3001
      MONGODB_URI: "mongodb://qjcoder:qjcoder@mongodb:27017"
    networks:
      - red
    depends_on:
      - mongodb
    volumes:
      - ./backend/shared-models:/app/src/models

  #TEST SERVICE
  test-service:
    build:
      context: ./backend/test-service
      dockerfile: Dockerfile
    container_name: test-service
    ports:
      - "3100:3100"
    environment:
      PORT_TEST_SERVICE: 3100
      MONGODB_URI: "mongodb://qjcoder:qjcoder@mongodb:27017"
    networks:
      - red
    depends_on:
      - mongodb
    volumes:
      - ./backend/shared-models:/app/src/models

  #MENU-MANAGEMENT-SERVICE
  menu-management-service:
    build:
      context: ./backend/menu-management-service
      dockerfile: Dockerfile
    container_name: menu-management-service
    ports:
      - "4000:4000"
    environment:
      PORT_MENU_MANAGEMENT_SERVICE: 4000
      #MONGODB_URI: "mongodb://qjcoder:qjcoder@mongodb:27017"
      #CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      #CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      #CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
      #MONGODB_ATLAS
      #MONGODB_URI: ${MONGODB_URI}

    networks:
      - red
    depends_on:
      - mongodb
    volumes:
      - ./backend/shared-models:/app/src/models

networks:
  red:
    driver: bridge
volumes:
  mongodb_data:
