[{
      name: "Ceviche",
      category: "Mariscos",
      type: "Entrada",
      price: 15.99,
      description: "Pescado fresco marinado en limón con ají y cebolla.",
      image: {
        publicId: "ceviche123",
        url: "https://ejemplo.com/ceviche.jpg",
      },
      ratings: [],
    },
    {
      name: "Lomo Saltado",
      category: "Carnes",
      type: "Principal",
      price: 18.99,
      description: "Trozos de carne salteados con verduras y papas fritas.",
      image: {
        publicId: "lomoSaltado456",
        url: "https://ejemplo.com/lomo_saltado.jpg",
      },
      ratings: [],
    },
    {
      name: "Aji de Gallina",
      category: "Pollo",
      type: "Principal",
      price: 16.99,
      description: "Pollo deshilachado en una salsa cremosa de ají amarillo.",
      image: {
        publicId: "ajiGallina789",
        url: "https://ejemplo.com/aji_de_gallina.jpg",
      },
      ratings: [],
    },
    {
      name: "Rocoto Relleno",
      category: "Aperitivo",
      type: "Entrada",
      price: 14.99,
      description: "Pimiento rocoto relleno de carne, papas y queso gratinado.",
      image: {
        publicId: "rocotoRelleno101",
        url: "https://ejemplo.com/rocoto_relleno.jpg",
      },
      ratings: [],
    },
    {
      name: "Causa Limeña",
      category: "Aperitivo",
      type: "Entrada",
      price: 12.99,
      description: "Puré de papa amarilla con ají, relleno de atún o pollo.",
      image: {
        publicId: "causaLimeña202",
        url: "https://ejemplo.com/causa_limena.jpg",
      },
      ratings: [],
    },
    {
      name: "Arroz con Mariscos",
      category: "Mariscos",
      type: "Principal",
      price: 22.99,
      description: "Arroz con una mezcla de mariscos en salsa de ajo y vino blanco.",
      image: {
        publicId: "arrozMariscos303",
        url: "https://ejemplo.com/arroz_con_mariscos.jpg",
      },
      ratings: [],
    },
    {
      name: "Anticuchos",
      category: "Carnes",
      type: "Entrada",
      price: 13.99,
      description: "Brochetas de corazón de res marinadas en ají panca.",
      image: {
        publicId: "anticuchos404",
        url: "https://ejemplo.com/anticuchos.jpg",
      },
      ratings: [],
    },
    {
      name: "Tacu Tacu",
      category: "Carnes",
      type: "Principal",
      price: 17.99,
      description: "Arroz y frijoles mezclados y fritos, servidos con carne a la parrilla.",
      image: {
        publicId: "tacuTacu505",
        url: "https://ejemplo.com/tacu_tacu.jpg",
      },
      ratings: [],
    },
    {
      name: "Papa a la Huancaína",
      category: "Aperitivo",
      type: "Entrada",
      price: 11.99,
      description: "Papas cocidas cubiertas con salsa de queso, ají amarillo y nueces.",
      image: {
        publicId: "papaHuancaína606",
        url: "https://ejemplo.com/papa_a_la_huancaina.jpg",
      },
      ratings: [],
    },
    {
      name: "Seco de Cordero",
      category: "Carnes",
      type: "Principal",
      price: 19.99,
      description: "Cordero cocido a fuego lento en una salsa de cilantro y cerveza.",
      image: {
        publicId: "secoCordero707",
        url: "https://ejemplo.com/seco_de_cordero.jpg",
      },
      ratings: [],
    },
    {
      name: "Chaufa de Pollo",
      category: "Pollo",
      type: "Principal",
      price: 16.99,
      description: "Arroz frito con pollo, huevo, cebolla, y salsa de soja.",
      image: {
        publicId: "chaufaPollo808",
        url: "https://ejemplo.com/chaufa_de_pollo.jpg",
      },
      ratings: [],
    },
    {
      name: "Mazamorra Morada",
      category: "Postre",
      type: "Postre",
      price: 8.99,
      description: "Postre de maíz morado con frutas y canela.",
      image: {
        publicId: "mazamorraMorada909",
        url: "https://ejemplo.com/mazamorra_morada.jpg",
      },
      ratings: [],
    },
    {
      name: "Huancaina de Pollo",
      category: "Pollo",
      type: "Principal",
      price: 17.99,
      description: "Pollo a la parrilla con salsa de ají amarillo y queso.",
      image: {
        publicId: "huancainaPollo1010",
        url: "https://ejemplo.com/huancaina_de_pollo.jpg",
      },
      ratings: [],
    },
    {
      name: "Picarones",
      category: "Postre",
      type: "Postre",
      price: 10.99,
      description: "Masitas de calabaza y camote fritas, bañadas en miel de chancaca.",
      image: {
        publicId: "picarones1111",
        url: "https://ejemplo.com/picarones.jpg",
      },
      ratings: [],
    },
    {
      name: "Ají de Gallina",
      category: "Pollo",
      type: "Principal",
      price: 15.99,
      description: "Pollo desmenuzado en una salsa cremosa de ají amarillo y nueces.",
      image: {
        publicId: "ajiGallina1212",
        url: "https://ejemplo.com/aji_de_gallina_2.jpg",
      },
      ratings: [],
    },
    {
      name: "Tiradito",
      category: "Mariscos",
      type: "Entrada",
      price: 17.99,
      description: "Pescado cortado en tiras delgadas y marinado en salsa de limón y ají.",
      image: {
        publicId: "tiradito1313",
        url: "https://ejemplo.com/tiradito.jpg",
      },
      ratings: [],
    },
    {
      name: "Chupe de Camarones",
      category: "Mariscos",
      type: "Principal",
      price: 21.99,
      description: "Sopa espesa de camarones con maíz, queso y huevos.",
      image: {
        publicId: "chupeCamarones1414",
        url: "https://ejemplo.com/chupe_de_camarones.jpg",
      },
      ratings: [],
    },
    {
      name: "Tamal",
      category: "Aperitivo",
      type: "Entrada",
      price: 13.99,
      description: "Masa de maíz rellena de carne o pollo, envuelta en hojas de plátano.",
      image: {
        publicId: "tamal1515",
        url: "https://ejemplo.com/tamal.jpg",
      },
      ratings: [],
    },
    {
      name: "Pisco Sour",
      category: "Bebida",
      type: "Bebida",
      price: 9.99,
      description: "Cóctel peruano a base de pisco, limón, jarabe de goma y clara de huevo.",
      image: {
        publicId: "piscoSour1616",
        url: "https://ejemplo.com/pisco_sour.jpg",
      },
      ratings: [],
    },
    {
      name: "Olluquito con Charqui",
      category: "Carnes",
      type: "Principal",
      price: 18.99,
      description: "Estofado de ollucos con carne de res seca.",
      image: {
        publicId: "olluquitoCharqui1717",
        url: "https://ejemplo.com/olluquito_con_charqui.jpg",
      },
      ratings: [],
    },
    {
      name: "Arroz con Pato",
      category: "Aves",
      type: "Principal",
      price: 19.99,
      description: "Arroz preparado con pato y mezclado con cerveza negra.",
      image: {
        publicId: "arrozPato1818",
        url: "https://ejemplo.com/arroz_con_pato.jpg",
      },
      ratings: [],
    },
    {
      name: "Sudado de Pescado",
      category: "Mariscos",
      type: "Principal",
      price: 20.99,
      description: "Pescado cocido al vapor con tomate, cebolla y ají.",
      image: {
        publicId: "sudadoPescado1919",
        url: "https://ejemplo.com/sudado_de_pescado.jpg",
      },
      ratings: [],
    },
    {
      name: "Cau Cau",
      category: "Carnes",
      type: "Principal",
      price: 16.99,
      description: "Guiso de mondongo con papa y ají amarillo.",
      image: {
        publicId: "cauCau2020",
        url: "https://ejemplo.com/cau_cau.jpg",
      },
      ratings: [],
    },
    {
      name: "Chicharrón de Pescado",
      category: "Mariscos",
      type: "Entrada",
      price: 14.99,
      description: "Pescado frito acompañado de yuca y salsa criolla.",
      image: {
        publicId: "chicharronPescado2121",
        url: "https://ejemplo.com/chicharron_de_pescado.jpg",
      },
      ratings: [],
    },
    {
      name: "Canchán",
      category: "Aperitivo",
      type: "Entrada",
      price: 11.99,
      description: "Variedad de carnes frías y quesos con guarniciones.",
      image: {
        publicId: "canchan2222",
        url: "https://ejemplo.com/canchan.jpg",
      },
      ratings: [],
    },
    {
      name: "Arroz Zambito",
      category: "Postre",
      type: "Postre",
      price: 8.99,
      description: "Arroz con leche y chancaca, decorado con coco rallado.",
      image: {
        publicId: "arrozZambito2323",
        url: "https://ejemplo.com/arroz_zambito.jpg",
      },
      ratings: [],
    },
    {
      name: "Papa Rellena",
      category: "Aperitivo",
      type: "Entrada",
      price: 12.99,
      description: "Papa rellena de carne, huevo y aceitunas, empanizada y frita.",
      image: {
        publicId: "papaRellena2424",
        url: "https://ejemplo.com/papa_rellena.jpg",
      },
      ratings: [],
    },
    {
      name: "Mondonguito a la Italiana",
      category: "Carnes",
      type: "Entrada",
      price: 13.99,
      description: "Mondongo en salsa de tomate, cebolla y ají amarillo.",
      image: {
        publicId: "mondonguitoItaliana2525",
        url: "https://ejemplo.com/mondonguito_a_la_italiana.jpg",
      },
      ratings: [],
    },
    {
      name: "Suspiro a la Limeña",
      category: "Postre",
      type: "Postre",
      price: 9.99,
      description: "Dulce de leche cubierto con merengue italiano.",
      image: {
        publicId: "suspiroLimeña2626",
        url: "https://ejemplo.com/suspiro_a_la_limena.jpg",
      },
      ratings: [],
    },
    {
      name: "Pollo a la Brasa",
      category: "Pollo",
      type: "Principal",
      price: 21.99,
      description: "Pollo marinado y asado a la parrilla con especias.",
      image: {
        publicId: "polloBrasa2727",
        url: "https://ejemplo.com/pollo_a_la_brasa.jpg",
      },
      ratings: [],
    },]
  